version: 2.1
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    docker:
      - image: cimg/python:3.8.5
    steps:
    - checkout
    - python/install-packages
    - run:
        name: Run django tests
        command: |
            pipenv run python ./martor_demo/manage.py test
    - store_test_results:
        path: test-results
    - store_artifacts:
        path: test-results
        destination: tr1
